services:
  db-product:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_product:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-product:5432/product_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      FEIGN_PRODUCT_URL: http://172.21.0.3:8081/api/v1/categories
    ports:
      - "8082:8082"
    depends_on:
      - db-product

volumes:
  db_data_product:
