spring:
  application:
    name: product-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/product_db
    username: postgres
    password: password

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

feign:
  product:
    url: http://localhost:8081/api/v1/categories

server:
  port: 8082